# This is a basic workflow to help you get started with Actions

name: first_action 

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
      - name: list folder
        run: ls
      - name: where am i
        run: pwd
 # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - name: second list folder
        run: ls
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          cat README.md
          echo ==================
          cat 1
          echo Add other actions to build,
          echo test, and deploy your project.
      
  build2:
    # The type of runner that the job will run on
      runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
      steps:
        - name: run a one line scrip
          run: echo Hello Shai! 
          

